# Generated by Django 5.1.5 on 2025-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
